name: Run tests

on: 
  push: 

jobs: 
  test: 
    runs-on: ubuntu-latest 
    container: 
      image: node:22-alpine
    steps:
      - run: npm ci --legacy-peer-deps
      - run: npm run test:once