name: Run tests

on: 
  push: 

jobs: 
  test: 
    runs-on: ubuntu-latest 
    container: 
      image: node:22-alpine
    steps:
      - uses: actions/checkout@v6
      - run: npm ci
      - run: npm run test:once